// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"
)

type Catalog struct {
	ID       string    `json:"id"`
	Source   string    `json:"source"`
	SyncedAt time.Time `json:"synced_at"`
}

type Column struct {
	ID       int64  `json:"id"`
	TableID  int64  `json:"table_id"`
	Name     string `json:"name"`
	Type     string `json:"type"`
	Nullable bool   `json:"nullable"`
}

type Schema struct {
	ID        int64  `json:"id"`
	CatalogID string `json:"catalog_id"`
	Name      string `json:"name"`
}

type Table struct {
	ID       int64  `json:"id"`
	SchemaID int64  `json:"schema_id"`
	Name     string `json:"name"`
}
